name: riddhi_clone
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  add_to_cart_animation: ^2.0.4
  collection: ^1.17.0
  connectivity_plus: ^6.1.1

  dartz: ^0.10.1
  defer_pointer: ^0.0.2
  device_info_plus: ^11.3.0
  device_preview: ^1.2.0
  dropdown_button2: ^2.3.9
  envied: ^1.0.0
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  flutter_laravel_form_validation: ^1.0.4
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.4.4
  flutter_riverpod: ^2.6.1
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.17
  flutter_typeahead: ^5.2.0
  gap: ^3.0.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  image_cropper: ^8.1.0
  import_sorter: ^4.6.0
  internet_connection_checker_plus: ^2.7.0
  intl: ^0.20.1
  master_utility: ^0.0.16
  mobile_scanner: ^6.0.3
  mobkit_dashed_border: ^0.0.7
  open_file: ^3.5.10
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^11.4.0
  pin_code_fields: ^8.0.1
  pull_to_refresh: ^2.0.0
  qr_code_scanner_plus: ^2.0.7
  remove_emoji_input_formatter: ^0.0.1+1
  sentry_flutter: ^8.12.0
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^28.1.41
  syncfusion_flutter_datepicker: ^28.2.12
  timelines_plus: ^1.0.4
  toastification: ^2.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.13
  danger_core: ^2.0.0
  envied_generator: ^1.0.0
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

dependency_overrides:
  intl:

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/colors/
    - assets/icons/
    - assets/languages/
    - assets/images/
    - assets/documents/terms_&_condition.pdf

  fonts:
    - family: Heebo
      fonts:
        - asset: assets/fonts/Heebo-Light.ttf
        - asset: assets/fonts/Heebo-Regular.ttf
        - asset: assets/fonts/Heebo-Medium.ttf
        - asset: assets/fonts/Heebo-SemiBold.ttf
        - asset: assets/fonts/Heebo-Bold.ttf
        - asset: assets/fonts/Heebo-ExtraBold.ttf
    - family: Overlock
      fonts:
        - asset: assets/fonts/Overlock-Regular.ttf
        - asset: assets/fonts/Overlock-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/config/assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true
    rive: true
    lottie: true

  assets:
    enabled: true

    exclude:
      - .env.development
      - .env.production

    outputs:
      class_name: AppAssets
      package_parameter_enabled: false
      style: dot-delimiter

  fonts:
    enabled: true
    outputs:
      class_name: AppFonts

  colors:
    enabled: true
    outputs:
      class_name: AppColors
    inputs:
      - assets/colors/colors.xml

